spring.application.name=edupro-uep

spring.datasource.url=jdbc:postgresql://localhost:5432/edupro_uep
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
